[build]
  publish = "."
  ignore = "git diff --quiet HEAD~1 HEAD ."

[build.processing]
  skip_ssr = true

# Custom domain
[[redirects]]
  from = "/go/*"
  to = "http://localhost:3001/go/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
